// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airbnb.Models
{
    public partial class Booking
    {
        public Booking()
        {
            Invoices = new HashSet<Invoice>();
            Rooms = new HashSet<Room>();
        }

        [Key]
        public int BookingId { get; set; }
        [NotMapped]
        public DateOnly? DateFrom { get; set; }
        [NotMapped]
        public DateOnly? DateTo { get; set; }
        public int? RoomCount { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalPrice { get; set; }
        public int? Hotel_Id { get; set; }
        public int? Guest_Id { get; set; }

        [ForeignKey("Hotel_Id")]
        [InverseProperty("Bookings")]
        public virtual Hotel Hotel { get; set; }
        [InverseProperty("Booking")]
        public virtual ICollection<Invoice> Invoices { get; set; }

        [ForeignKey("Booking_Id")]
        [InverseProperty("Bookings")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}